language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

install: 
  - npm install

before_script:

script: 
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $travis_token
  local_dir: dist/  
  on:
    branch: master